const { Router } = require('express')
const router = Router()
const { mailVerification, mailChangeReq, getmailchangeID} = require('../controllers/TaskControllers')
const { setData, getData, addSolution, deleteSolution, updateSolution, uploadedIssues, getParticularSolution, issueStatus} = require('../controllers/IssueController')
const {signUpData, logInUserData, setCurrentUser, getCurrentUser, deleteCurrentUser, getParticularUser, getAllUsers, deleteUser, updateUser} = require('../controllers/UserControllers')
const { messages } = require('../controllers/MessageController')

router.post('/setData', setData)
router.get('/getData', getData)
router.post('/addSolution', addSolution)
router.post('/signupData', signUpData)
router.post('/loginData', logInUserData)
router.post('/setCurrentUser', setCurrentUser)
router.get('/getCurrentUser', getCurrentUser)
router.delete('/deletecurrentuser', deleteCurrentUser)
router.post('/getparticularuser', getParticularUser)
router.get('/getallusers', getAllUsers)
router.post('/uploadedIssues', uploadedIssues)
router.post('/updatesolution', updateSolution)
router.post('/mailverification', mailVerification)
router.delete('/deleteuser', deleteUser)
router.post('/adminupdateuser', updateUser)
router.post('/deletesolution', deleteSolution)
router.post('/mailupdatereq', mailChangeReq)
router.get('/getmailreqIDs', getmailchangeID)
router.post('/getParticularSolution', getParticularSolution)
router.put('/issueStatus', issueStatus)
// router.get('/usermessages',messages )



module.exports = router